### ISSUE TITLE
Not work with Home Assistant 0.109.6

### ISSUE THREAD

**Issue by mikesrus** [Limych/ha-beward#4]
when install via HACS does not start. I got this message in log

Уровень: ERROR
Logger: homeassistant.setup
Source: custom_components/beward/__init__.py:87
First occurred: 19:37:43 (1 occurrences)
Last logged: 19:37:43

Error during setup of component beward
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 175, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/beward/__init__.py", line 87, in setup
    stream=stream)
  File "/usr/local/lib/python3.7/site-packages/beward/__init__.py", line 53, in factory
    model = bwd.system_info.get('DeviceModel')
  File "/usr/local/lib/python3.7/site-packages/beward/core.py", line 237, in system_info
    self._sysinfo = self.get_info('systeminfo')
  File "/usr/local/lib/python3.7/site-packages/beward/core.py", line 221, in get_info
    'action': 'get',
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by Limych** [comment]
Правила и шаблоны придуманы для того, чтобы всем было удобно. Я понимаю, что у нас, у русских, богатая школа нарушать правила, но отнюдь не поддерживаю это.
В этом репозитории дан шаблон для создания багрепротов. Там есть инструкция, что должно быть минимально указано в сообщении. Вы всё это проигнорировали. Но без этой информации я не могу Вам помочь, извините.

Issues not containing the minimum requirements will be closed:

- Issues without a description (using the header is not good enough) will be closed.
- Issues without debug logging will be closed.
- Issues without configuration will be closed
